CREATE TABLE usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_sefaz VARCHAR(255) NOT NULL,
    user_sefaz VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id),
    CONSTRAINT fk_client FOREIGN KEY (id) REFERENCES cliente(id) ON DELETE CASCADE ON UPDATE CASCADE
);