CREATE TABLE empresa (
    id BIGINT NOT NULL AUTO_INCREMENT,
    cnpj VARCHAR(255) NOT NULL UNIQUE KEY,
    nome VARCHAR(255) NOT NULL,
    id_usuario BIGINT NOT NULL, 
    PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);